<a href="https://colab.research.google.com/github/jayshivankar/Linear_Algebra_for_ML/blob/main/Linear_Algebra_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Inverse of a matrix

    The inverse of a matrix A is denoted by A^(-1)
        (A x A^(-1) = I)

    Not all matrix has inverse only the square matrix with non zero determinant are invertable

    Example:

        A = [[4, 7],
             [2, 6]]

                    (1)
      A^(-1) = ------------ [[6  -7]
                (4x6 - 7x2)  [-2  4]]

            
             = (1/10) [[6  -7]
                      [-2  4]]

             = [[ 0.6, -0.7],
                [-0.2,  0.4]


    Example:

        A = [[3, 2, 1],
             [1, 1, 2],
             [2, 1, 3]]

    
        det(A) = 3(3-2) - 2(3-4) + 1(1-2)
               = 3 + 2 - 1
               = 4

        - cofactor matrix (determinants of 2x2 minors with alternative signs)
        
        C = [ (1x3-1x2)  -(1x3-2x2)   (1x1-2x1)
             -(2x3-1x1)   (3x3-1x2)  -(3x1-2x2)
              (2x2-1x1)  -(3x2-1x1)   (3x1-1x2)]

        C = [ 1   1  -1
             -5   7   1
              3  -5   1]

        - Adjucate(A) is the transpose of cofactor matrix

        Adj(A) = [ 1  -5   3
                   1   7  -5
                  -1   1   1]

                      (1)       [[ 1  -5   3]
         A^(-1) = ------------   [ 1   7  -5]
                       4         [-1   1   1]]

        
         A^(-1) = [[ 0.25   -1.25    0.75]
                   [ 0.25    1.75   -1.25]
                   [-0.25    0.25    0.25]]                            

                        



In [ ]:
import numpy as np

A = np.array([[3, 2, 1],[1, 1, 2],[2, 1, 3]])
A_inv = np.linalg.inv(A)
print(A_inv)

[[ 0.25 -1.25  0.75]
 [ 0.25  1.75 -1.25]
 [-0.25  0.25  0.25]]


# Eigenvalues & Eigenvector

     1. This is essential in PCA (Principle Component Analysis), transformations, clustering.
     2. This helps to simplfy the complex pattern.

     For a Square matrix A, an eigenvector v and its corresponding eigenvalue λ satisfies

        * Av = λv

    This equation mean:
        - "A" transforms the vector "v" but doesnot change the direction.
        - The vector is only stretched or shrunk by the factor λ (eigenvalue)

    Example:

    If "A" represents transformation, applying "A" to a eigenvector results in a scaled version of same vector.
        - Eigenvector - direction remains unchanged
        - Eigenvalue - scaling factor (stretch/shrunk)


# Computing Eigen value & eigen vector

    - Given  a square matrix "A", we compute eigenvector by solving,
        det(A - λI) = 0

        where,
        - I is identity matrix
        - λ represents eigenvalue

    - Once we find λ, we solve for eigenvector using:
        (A - λI)v = 0

    - Example calculation

        A = [4  -2
             1   1]

        Step 1: Find Eigenvalue

            Solve : det(A-λI) = 0

                # det [[4-λ   -2
                         1    1-λ]]   =  0

                # (4-λ)(1-λ) + 2 = 0
                # (4-4λ-λ+λ^2+2) = 0
                # λ^2 - 5λ + 6 = 0
                # (λ-2)(λ-3) = 0

                So the eigen value is λ = 2, 3

        Step 2: Find the Eigenvector

            Solve : λ = 2

                # (A - λI)v = 0
                # (A - 2I)v = 0

                # [[4-2  -2]    [[x]    =   [[0]
                   [1   1-2]]    [y]]        [0]]

                # 2x - 2y = 0
                # 2x = 2y
                # x = y

                # Eigenvector of λ=2 is any muliple of [1,1]

            Solve : λ = 3

                # (A - λI)v = 0
                # (A - 3I)v = 0

                # [[4-3  -2]    [[x]    =   [[0]
                   [1   1-3]]    [y]]        [0]]

                # x - 2y = 0
                # x = 2y

                # Eigenvector of λ=3 is any muliple of [2,1]






In [ ]:
# Python implementation
A = np.array([[4, -2], [1,1]])

# compute the eigenvalue and eigenvector
eigenvalue, eigenvector = np.linalg.eig(A)

# output
print('Eigenvalue:', eigenvalue)
print('Eigenvector:\n', eigenvector)

Eigenvalue: [3. 2.]
Eigenvector:
 [[0.89442719 0.70710678]
 [0.4472136  0.70710678]]
